// Code generated by go-swagger; DO NOT EDIT.

package catalog

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/caner-cetin/halycon/internal/amazon/catalog/models"
)

// SearchCatalogItemsReader is a Reader for the SearchCatalogItems structure.
type SearchCatalogItemsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SearchCatalogItemsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSearchCatalogItemsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewSearchCatalogItemsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewSearchCatalogItemsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewSearchCatalogItemsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 413:
		result := NewSearchCatalogItemsRequestEntityTooLarge()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 415:
		result := NewSearchCatalogItemsUnsupportedMediaType()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewSearchCatalogItemsTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewSearchCatalogItemsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 503:
		result := NewSearchCatalogItemsServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /catalog/2022-04-01/items] searchCatalogItems", response, response.Code())
	}
}

// NewSearchCatalogItemsOK creates a SearchCatalogItemsOK with default headers values
func NewSearchCatalogItemsOK() *SearchCatalogItemsOK {
	return &SearchCatalogItemsOK{}
}

/*
SearchCatalogItemsOK describes a response with status code 200, with default header values.

Success.
*/
type SearchCatalogItemsOK struct {

	/* Your rate limit (requests per second) for this operation.
	 */
	XAmznRateLimitLimit string

	/* Unique request reference identifier.
	 */
	XAmznRequestID string

	Payload *models.ItemSearchResults
}

// IsSuccess returns true when this search catalog items o k response has a 2xx status code
func (o *SearchCatalogItemsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this search catalog items o k response has a 3xx status code
func (o *SearchCatalogItemsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this search catalog items o k response has a 4xx status code
func (o *SearchCatalogItemsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this search catalog items o k response has a 5xx status code
func (o *SearchCatalogItemsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this search catalog items o k response a status code equal to that given
func (o *SearchCatalogItemsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the search catalog items o k response
func (o *SearchCatalogItemsOK) Code() int {
	return 200
}

func (o *SearchCatalogItemsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /catalog/2022-04-01/items][%d] searchCatalogItemsOK %s", 200, payload)
}

func (o *SearchCatalogItemsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /catalog/2022-04-01/items][%d] searchCatalogItemsOK %s", 200, payload)
}

func (o *SearchCatalogItemsOK) GetPayload() *models.ItemSearchResults {
	return o.Payload
}

func (o *SearchCatalogItemsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header x-amzn-RateLimit-Limit
	hdrXAmznRateLimitLimit := response.GetHeader("x-amzn-RateLimit-Limit")

	if hdrXAmznRateLimitLimit != "" {
		o.XAmznRateLimitLimit = hdrXAmznRateLimitLimit
	}

	// hydrates response header x-amzn-RequestId
	hdrXAmznRequestID := response.GetHeader("x-amzn-RequestId")

	if hdrXAmznRequestID != "" {
		o.XAmznRequestID = hdrXAmznRequestID
	}

	o.Payload = new(models.ItemSearchResults)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSearchCatalogItemsBadRequest creates a SearchCatalogItemsBadRequest with default headers values
func NewSearchCatalogItemsBadRequest() *SearchCatalogItemsBadRequest {
	return &SearchCatalogItemsBadRequest{}
}

/*
SearchCatalogItemsBadRequest describes a response with status code 400, with default header values.

Request has missing or invalid parameters and cannot be parsed.
*/
type SearchCatalogItemsBadRequest struct {

	/* Your rate limit (requests per second) for this operation.
	 */
	XAmznRateLimitLimit string

	/* Unique request reference identifier.
	 */
	XAmznRequestID string

	Payload *models.ErrorList
}

// IsSuccess returns true when this search catalog items bad request response has a 2xx status code
func (o *SearchCatalogItemsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this search catalog items bad request response has a 3xx status code
func (o *SearchCatalogItemsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this search catalog items bad request response has a 4xx status code
func (o *SearchCatalogItemsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this search catalog items bad request response has a 5xx status code
func (o *SearchCatalogItemsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this search catalog items bad request response a status code equal to that given
func (o *SearchCatalogItemsBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the search catalog items bad request response
func (o *SearchCatalogItemsBadRequest) Code() int {
	return 400
}

func (o *SearchCatalogItemsBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /catalog/2022-04-01/items][%d] searchCatalogItemsBadRequest %s", 400, payload)
}

func (o *SearchCatalogItemsBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /catalog/2022-04-01/items][%d] searchCatalogItemsBadRequest %s", 400, payload)
}

func (o *SearchCatalogItemsBadRequest) GetPayload() *models.ErrorList {
	return o.Payload
}

func (o *SearchCatalogItemsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header x-amzn-RateLimit-Limit
	hdrXAmznRateLimitLimit := response.GetHeader("x-amzn-RateLimit-Limit")

	if hdrXAmznRateLimitLimit != "" {
		o.XAmznRateLimitLimit = hdrXAmznRateLimitLimit
	}

	// hydrates response header x-amzn-RequestId
	hdrXAmznRequestID := response.GetHeader("x-amzn-RequestId")

	if hdrXAmznRequestID != "" {
		o.XAmznRequestID = hdrXAmznRequestID
	}

	o.Payload = new(models.ErrorList)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSearchCatalogItemsForbidden creates a SearchCatalogItemsForbidden with default headers values
func NewSearchCatalogItemsForbidden() *SearchCatalogItemsForbidden {
	return &SearchCatalogItemsForbidden{}
}

/*
SearchCatalogItemsForbidden describes a response with status code 403, with default header values.

Indicates that access to the resource is forbidden. Possible reasons include Access Denied, Unauthorized, Expired Token, or Invalid Signature.
*/
type SearchCatalogItemsForbidden struct {

	/* Unique request reference identifier.
	 */
	XAmznRequestID string

	Payload *models.ErrorList
}

// IsSuccess returns true when this search catalog items forbidden response has a 2xx status code
func (o *SearchCatalogItemsForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this search catalog items forbidden response has a 3xx status code
func (o *SearchCatalogItemsForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this search catalog items forbidden response has a 4xx status code
func (o *SearchCatalogItemsForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this search catalog items forbidden response has a 5xx status code
func (o *SearchCatalogItemsForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this search catalog items forbidden response a status code equal to that given
func (o *SearchCatalogItemsForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the search catalog items forbidden response
func (o *SearchCatalogItemsForbidden) Code() int {
	return 403
}

func (o *SearchCatalogItemsForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /catalog/2022-04-01/items][%d] searchCatalogItemsForbidden %s", 403, payload)
}

func (o *SearchCatalogItemsForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /catalog/2022-04-01/items][%d] searchCatalogItemsForbidden %s", 403, payload)
}

func (o *SearchCatalogItemsForbidden) GetPayload() *models.ErrorList {
	return o.Payload
}

func (o *SearchCatalogItemsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header x-amzn-RequestId
	hdrXAmznRequestID := response.GetHeader("x-amzn-RequestId")

	if hdrXAmznRequestID != "" {
		o.XAmznRequestID = hdrXAmznRequestID
	}

	o.Payload = new(models.ErrorList)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSearchCatalogItemsNotFound creates a SearchCatalogItemsNotFound with default headers values
func NewSearchCatalogItemsNotFound() *SearchCatalogItemsNotFound {
	return &SearchCatalogItemsNotFound{}
}

/*
SearchCatalogItemsNotFound describes a response with status code 404, with default header values.

The resource specified does not exist.
*/
type SearchCatalogItemsNotFound struct {

	/* Your rate limit (requests per second) for this operation.
	 */
	XAmznRateLimitLimit string

	/* Unique request reference identifier.
	 */
	XAmznRequestID string

	Payload *models.ErrorList
}

// IsSuccess returns true when this search catalog items not found response has a 2xx status code
func (o *SearchCatalogItemsNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this search catalog items not found response has a 3xx status code
func (o *SearchCatalogItemsNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this search catalog items not found response has a 4xx status code
func (o *SearchCatalogItemsNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this search catalog items not found response has a 5xx status code
func (o *SearchCatalogItemsNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this search catalog items not found response a status code equal to that given
func (o *SearchCatalogItemsNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the search catalog items not found response
func (o *SearchCatalogItemsNotFound) Code() int {
	return 404
}

func (o *SearchCatalogItemsNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /catalog/2022-04-01/items][%d] searchCatalogItemsNotFound %s", 404, payload)
}

func (o *SearchCatalogItemsNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /catalog/2022-04-01/items][%d] searchCatalogItemsNotFound %s", 404, payload)
}

func (o *SearchCatalogItemsNotFound) GetPayload() *models.ErrorList {
	return o.Payload
}

func (o *SearchCatalogItemsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header x-amzn-RateLimit-Limit
	hdrXAmznRateLimitLimit := response.GetHeader("x-amzn-RateLimit-Limit")

	if hdrXAmznRateLimitLimit != "" {
		o.XAmznRateLimitLimit = hdrXAmznRateLimitLimit
	}

	// hydrates response header x-amzn-RequestId
	hdrXAmznRequestID := response.GetHeader("x-amzn-RequestId")

	if hdrXAmznRequestID != "" {
		o.XAmznRequestID = hdrXAmznRequestID
	}

	o.Payload = new(models.ErrorList)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSearchCatalogItemsRequestEntityTooLarge creates a SearchCatalogItemsRequestEntityTooLarge with default headers values
func NewSearchCatalogItemsRequestEntityTooLarge() *SearchCatalogItemsRequestEntityTooLarge {
	return &SearchCatalogItemsRequestEntityTooLarge{}
}

/*
SearchCatalogItemsRequestEntityTooLarge describes a response with status code 413, with default header values.

The request size exceeded the maximum accepted size.
*/
type SearchCatalogItemsRequestEntityTooLarge struct {

	/* Unique request reference identifier.
	 */
	XAmznRequestID string

	Payload *models.ErrorList
}

// IsSuccess returns true when this search catalog items request entity too large response has a 2xx status code
func (o *SearchCatalogItemsRequestEntityTooLarge) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this search catalog items request entity too large response has a 3xx status code
func (o *SearchCatalogItemsRequestEntityTooLarge) IsRedirect() bool {
	return false
}

// IsClientError returns true when this search catalog items request entity too large response has a 4xx status code
func (o *SearchCatalogItemsRequestEntityTooLarge) IsClientError() bool {
	return true
}

// IsServerError returns true when this search catalog items request entity too large response has a 5xx status code
func (o *SearchCatalogItemsRequestEntityTooLarge) IsServerError() bool {
	return false
}

// IsCode returns true when this search catalog items request entity too large response a status code equal to that given
func (o *SearchCatalogItemsRequestEntityTooLarge) IsCode(code int) bool {
	return code == 413
}

// Code gets the status code for the search catalog items request entity too large response
func (o *SearchCatalogItemsRequestEntityTooLarge) Code() int {
	return 413
}

func (o *SearchCatalogItemsRequestEntityTooLarge) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /catalog/2022-04-01/items][%d] searchCatalogItemsRequestEntityTooLarge %s", 413, payload)
}

func (o *SearchCatalogItemsRequestEntityTooLarge) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /catalog/2022-04-01/items][%d] searchCatalogItemsRequestEntityTooLarge %s", 413, payload)
}

func (o *SearchCatalogItemsRequestEntityTooLarge) GetPayload() *models.ErrorList {
	return o.Payload
}

func (o *SearchCatalogItemsRequestEntityTooLarge) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header x-amzn-RequestId
	hdrXAmznRequestID := response.GetHeader("x-amzn-RequestId")

	if hdrXAmznRequestID != "" {
		o.XAmznRequestID = hdrXAmznRequestID
	}

	o.Payload = new(models.ErrorList)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSearchCatalogItemsUnsupportedMediaType creates a SearchCatalogItemsUnsupportedMediaType with default headers values
func NewSearchCatalogItemsUnsupportedMediaType() *SearchCatalogItemsUnsupportedMediaType {
	return &SearchCatalogItemsUnsupportedMediaType{}
}

/*
SearchCatalogItemsUnsupportedMediaType describes a response with status code 415, with default header values.

The request payload is in an unsupported format.
*/
type SearchCatalogItemsUnsupportedMediaType struct {

	/* Unique request reference identifier.
	 */
	XAmznRequestID string

	Payload *models.ErrorList
}

// IsSuccess returns true when this search catalog items unsupported media type response has a 2xx status code
func (o *SearchCatalogItemsUnsupportedMediaType) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this search catalog items unsupported media type response has a 3xx status code
func (o *SearchCatalogItemsUnsupportedMediaType) IsRedirect() bool {
	return false
}

// IsClientError returns true when this search catalog items unsupported media type response has a 4xx status code
func (o *SearchCatalogItemsUnsupportedMediaType) IsClientError() bool {
	return true
}

// IsServerError returns true when this search catalog items unsupported media type response has a 5xx status code
func (o *SearchCatalogItemsUnsupportedMediaType) IsServerError() bool {
	return false
}

// IsCode returns true when this search catalog items unsupported media type response a status code equal to that given
func (o *SearchCatalogItemsUnsupportedMediaType) IsCode(code int) bool {
	return code == 415
}

// Code gets the status code for the search catalog items unsupported media type response
func (o *SearchCatalogItemsUnsupportedMediaType) Code() int {
	return 415
}

func (o *SearchCatalogItemsUnsupportedMediaType) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /catalog/2022-04-01/items][%d] searchCatalogItemsUnsupportedMediaType %s", 415, payload)
}

func (o *SearchCatalogItemsUnsupportedMediaType) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /catalog/2022-04-01/items][%d] searchCatalogItemsUnsupportedMediaType %s", 415, payload)
}

func (o *SearchCatalogItemsUnsupportedMediaType) GetPayload() *models.ErrorList {
	return o.Payload
}

func (o *SearchCatalogItemsUnsupportedMediaType) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header x-amzn-RequestId
	hdrXAmznRequestID := response.GetHeader("x-amzn-RequestId")

	if hdrXAmznRequestID != "" {
		o.XAmznRequestID = hdrXAmznRequestID
	}

	o.Payload = new(models.ErrorList)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSearchCatalogItemsTooManyRequests creates a SearchCatalogItemsTooManyRequests with default headers values
func NewSearchCatalogItemsTooManyRequests() *SearchCatalogItemsTooManyRequests {
	return &SearchCatalogItemsTooManyRequests{}
}

/*
SearchCatalogItemsTooManyRequests describes a response with status code 429, with default header values.

The frequency of requests was greater than allowed.
*/
type SearchCatalogItemsTooManyRequests struct {

	/* Unique request reference identifier.
	 */
	XAmznRequestID string

	Payload *models.ErrorList
}

// IsSuccess returns true when this search catalog items too many requests response has a 2xx status code
func (o *SearchCatalogItemsTooManyRequests) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this search catalog items too many requests response has a 3xx status code
func (o *SearchCatalogItemsTooManyRequests) IsRedirect() bool {
	return false
}

// IsClientError returns true when this search catalog items too many requests response has a 4xx status code
func (o *SearchCatalogItemsTooManyRequests) IsClientError() bool {
	return true
}

// IsServerError returns true when this search catalog items too many requests response has a 5xx status code
func (o *SearchCatalogItemsTooManyRequests) IsServerError() bool {
	return false
}

// IsCode returns true when this search catalog items too many requests response a status code equal to that given
func (o *SearchCatalogItemsTooManyRequests) IsCode(code int) bool {
	return code == 429
}

// Code gets the status code for the search catalog items too many requests response
func (o *SearchCatalogItemsTooManyRequests) Code() int {
	return 429
}

func (o *SearchCatalogItemsTooManyRequests) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /catalog/2022-04-01/items][%d] searchCatalogItemsTooManyRequests %s", 429, payload)
}

func (o *SearchCatalogItemsTooManyRequests) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /catalog/2022-04-01/items][%d] searchCatalogItemsTooManyRequests %s", 429, payload)
}

func (o *SearchCatalogItemsTooManyRequests) GetPayload() *models.ErrorList {
	return o.Payload
}

func (o *SearchCatalogItemsTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header x-amzn-RequestId
	hdrXAmznRequestID := response.GetHeader("x-amzn-RequestId")

	if hdrXAmznRequestID != "" {
		o.XAmznRequestID = hdrXAmznRequestID
	}

	o.Payload = new(models.ErrorList)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSearchCatalogItemsInternalServerError creates a SearchCatalogItemsInternalServerError with default headers values
func NewSearchCatalogItemsInternalServerError() *SearchCatalogItemsInternalServerError {
	return &SearchCatalogItemsInternalServerError{}
}

/*
SearchCatalogItemsInternalServerError describes a response with status code 500, with default header values.

An unexpected condition occurred that prevented the server from fulfilling the request.
*/
type SearchCatalogItemsInternalServerError struct {

	/* Unique request reference identifier.
	 */
	XAmznRequestID string

	Payload *models.ErrorList
}

// IsSuccess returns true when this search catalog items internal server error response has a 2xx status code
func (o *SearchCatalogItemsInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this search catalog items internal server error response has a 3xx status code
func (o *SearchCatalogItemsInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this search catalog items internal server error response has a 4xx status code
func (o *SearchCatalogItemsInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this search catalog items internal server error response has a 5xx status code
func (o *SearchCatalogItemsInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this search catalog items internal server error response a status code equal to that given
func (o *SearchCatalogItemsInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the search catalog items internal server error response
func (o *SearchCatalogItemsInternalServerError) Code() int {
	return 500
}

func (o *SearchCatalogItemsInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /catalog/2022-04-01/items][%d] searchCatalogItemsInternalServerError %s", 500, payload)
}

func (o *SearchCatalogItemsInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /catalog/2022-04-01/items][%d] searchCatalogItemsInternalServerError %s", 500, payload)
}

func (o *SearchCatalogItemsInternalServerError) GetPayload() *models.ErrorList {
	return o.Payload
}

func (o *SearchCatalogItemsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header x-amzn-RequestId
	hdrXAmznRequestID := response.GetHeader("x-amzn-RequestId")

	if hdrXAmznRequestID != "" {
		o.XAmznRequestID = hdrXAmznRequestID
	}

	o.Payload = new(models.ErrorList)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSearchCatalogItemsServiceUnavailable creates a SearchCatalogItemsServiceUnavailable with default headers values
func NewSearchCatalogItemsServiceUnavailable() *SearchCatalogItemsServiceUnavailable {
	return &SearchCatalogItemsServiceUnavailable{}
}

/*
SearchCatalogItemsServiceUnavailable describes a response with status code 503, with default header values.

Temporary overloading or maintenance of the server.
*/
type SearchCatalogItemsServiceUnavailable struct {

	/* Unique request reference identifier.
	 */
	XAmznRequestID string

	Payload *models.ErrorList
}

// IsSuccess returns true when this search catalog items service unavailable response has a 2xx status code
func (o *SearchCatalogItemsServiceUnavailable) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this search catalog items service unavailable response has a 3xx status code
func (o *SearchCatalogItemsServiceUnavailable) IsRedirect() bool {
	return false
}

// IsClientError returns true when this search catalog items service unavailable response has a 4xx status code
func (o *SearchCatalogItemsServiceUnavailable) IsClientError() bool {
	return false
}

// IsServerError returns true when this search catalog items service unavailable response has a 5xx status code
func (o *SearchCatalogItemsServiceUnavailable) IsServerError() bool {
	return true
}

// IsCode returns true when this search catalog items service unavailable response a status code equal to that given
func (o *SearchCatalogItemsServiceUnavailable) IsCode(code int) bool {
	return code == 503
}

// Code gets the status code for the search catalog items service unavailable response
func (o *SearchCatalogItemsServiceUnavailable) Code() int {
	return 503
}

func (o *SearchCatalogItemsServiceUnavailable) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /catalog/2022-04-01/items][%d] searchCatalogItemsServiceUnavailable %s", 503, payload)
}

func (o *SearchCatalogItemsServiceUnavailable) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /catalog/2022-04-01/items][%d] searchCatalogItemsServiceUnavailable %s", 503, payload)
}

func (o *SearchCatalogItemsServiceUnavailable) GetPayload() *models.ErrorList {
	return o.Payload
}

func (o *SearchCatalogItemsServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header x-amzn-RequestId
	hdrXAmznRequestID := response.GetHeader("x-amzn-RequestId")

	if hdrXAmznRequestID != "" {
		o.XAmznRequestID = hdrXAmznRequestID
	}

	o.Payload = new(models.ErrorList)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
