# values with placeholders are optional
amazon:
  # required for all operations
  auth:
    # client ID and secret of application
    client:
      id: 
      secret:
    # refresh token, acquired from self-authorizing the application
    refresh_token:
    endpoint: https://api.amazon.com/auth/o2/token
    # host for bearer token
    host: sellingpartnerapi-na.amazon.com
  # marketplace ids for all kinds of operations, US will be registered by default
  marketplace_id: 
    - ATVPDKIKX0DER
  fba:
    # required for creating FBA inbound shipment plans
    #
    # https://developer-docs.amazon.com/sp-api/lang-tr_TR/docs/fulfillment-inbound-api-v2024-03-20-reference#addressinput
    ship_from:
      # Street address information.
      address_line_1: 
      # Additional street address information, optional.
      address_line_2:
      city:
      # The name of the business, optional.
      company_name:
      # The country code in two-character ISO 3166-1 alpha-2 format, required, set to US by default.
      country_code: US
      # Optional.
      email:
      # The name of the individual who is the primary contact.
      name:
      phone_number: 
      postal_code:
      # The state or province code, required, albeit that docs indicate that it is optional.
      # TX, AZ, two-character code.
      state_or_province_code: 


