// Code generated by go-swagger; DO NOT EDIT.

package catalog

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/caner-cetin/halycon/internal/amazon/models"
)

// GetCatalogItemReader is a Reader for the GetCatalogItem structure.
type GetCatalogItemReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetCatalogItemReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetCatalogItemOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetCatalogItemBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetCatalogItemForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetCatalogItemNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 413:
		result := NewGetCatalogItemRequestEntityTooLarge()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 415:
		result := NewGetCatalogItemUnsupportedMediaType()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewGetCatalogItemTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetCatalogItemInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 503:
		result := NewGetCatalogItemServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /catalog/2022-04-01/items/{asin}] getCatalogItem", response, response.Code())
	}
}

// NewGetCatalogItemOK creates a GetCatalogItemOK with default headers values
func NewGetCatalogItemOK() *GetCatalogItemOK {
	return &GetCatalogItemOK{}
}

/*
GetCatalogItemOK describes a response with status code 200, with default header values.

Success.
*/
type GetCatalogItemOK struct {

	/* Your rate limit (requests per second) for this operation.
	 */
	XAmznRateLimitLimit string

	/* Unique request reference identifier.
	 */
	XAmznRequestID string

	Payload *models.Item
}

// IsSuccess returns true when this get catalog item o k response has a 2xx status code
func (o *GetCatalogItemOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get catalog item o k response has a 3xx status code
func (o *GetCatalogItemOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get catalog item o k response has a 4xx status code
func (o *GetCatalogItemOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get catalog item o k response has a 5xx status code
func (o *GetCatalogItemOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get catalog item o k response a status code equal to that given
func (o *GetCatalogItemOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get catalog item o k response
func (o *GetCatalogItemOK) Code() int {
	return 200
}

func (o *GetCatalogItemOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /catalog/2022-04-01/items/{asin}][%d] getCatalogItemOK %s", 200, payload)
}

func (o *GetCatalogItemOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /catalog/2022-04-01/items/{asin}][%d] getCatalogItemOK %s", 200, payload)
}

func (o *GetCatalogItemOK) GetPayload() *models.Item {
	return o.Payload
}

func (o *GetCatalogItemOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header x-amzn-RateLimit-Limit
	hdrXAmznRateLimitLimit := response.GetHeader("x-amzn-RateLimit-Limit")

	if hdrXAmznRateLimitLimit != "" {
		o.XAmznRateLimitLimit = hdrXAmznRateLimitLimit
	}

	// hydrates response header x-amzn-RequestId
	hdrXAmznRequestID := response.GetHeader("x-amzn-RequestId")

	if hdrXAmznRequestID != "" {
		o.XAmznRequestID = hdrXAmznRequestID
	}

	o.Payload = new(models.Item)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCatalogItemBadRequest creates a GetCatalogItemBadRequest with default headers values
func NewGetCatalogItemBadRequest() *GetCatalogItemBadRequest {
	return &GetCatalogItemBadRequest{}
}

/*
GetCatalogItemBadRequest describes a response with status code 400, with default header values.

Request has missing or invalid parameters and cannot be parsed.
*/
type GetCatalogItemBadRequest struct {

	/* Your rate limit (requests per second) for this operation.
	 */
	XAmznRateLimitLimit string

	/* Unique request reference identifier.
	 */
	XAmznRequestID string

	Payload *models.ErrorList
}

// IsSuccess returns true when this get catalog item bad request response has a 2xx status code
func (o *GetCatalogItemBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get catalog item bad request response has a 3xx status code
func (o *GetCatalogItemBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get catalog item bad request response has a 4xx status code
func (o *GetCatalogItemBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get catalog item bad request response has a 5xx status code
func (o *GetCatalogItemBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get catalog item bad request response a status code equal to that given
func (o *GetCatalogItemBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get catalog item bad request response
func (o *GetCatalogItemBadRequest) Code() int {
	return 400
}

func (o *GetCatalogItemBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /catalog/2022-04-01/items/{asin}][%d] getCatalogItemBadRequest %s", 400, payload)
}

func (o *GetCatalogItemBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /catalog/2022-04-01/items/{asin}][%d] getCatalogItemBadRequest %s", 400, payload)
}

func (o *GetCatalogItemBadRequest) GetPayload() *models.ErrorList {
	return o.Payload
}

func (o *GetCatalogItemBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header x-amzn-RateLimit-Limit
	hdrXAmznRateLimitLimit := response.GetHeader("x-amzn-RateLimit-Limit")

	if hdrXAmznRateLimitLimit != "" {
		o.XAmznRateLimitLimit = hdrXAmznRateLimitLimit
	}

	// hydrates response header x-amzn-RequestId
	hdrXAmznRequestID := response.GetHeader("x-amzn-RequestId")

	if hdrXAmznRequestID != "" {
		o.XAmznRequestID = hdrXAmznRequestID
	}

	o.Payload = new(models.ErrorList)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCatalogItemForbidden creates a GetCatalogItemForbidden with default headers values
func NewGetCatalogItemForbidden() *GetCatalogItemForbidden {
	return &GetCatalogItemForbidden{}
}

/*
GetCatalogItemForbidden describes a response with status code 403, with default header values.

Indicates that access to the resource is forbidden. Possible reasons include Access Denied, Unauthorized, Expired Token, or Invalid Signature.
*/
type GetCatalogItemForbidden struct {

	/* Unique request reference identifier.
	 */
	XAmznRequestID string

	Payload *models.ErrorList
}

// IsSuccess returns true when this get catalog item forbidden response has a 2xx status code
func (o *GetCatalogItemForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get catalog item forbidden response has a 3xx status code
func (o *GetCatalogItemForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get catalog item forbidden response has a 4xx status code
func (o *GetCatalogItemForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this get catalog item forbidden response has a 5xx status code
func (o *GetCatalogItemForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this get catalog item forbidden response a status code equal to that given
func (o *GetCatalogItemForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the get catalog item forbidden response
func (o *GetCatalogItemForbidden) Code() int {
	return 403
}

func (o *GetCatalogItemForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /catalog/2022-04-01/items/{asin}][%d] getCatalogItemForbidden %s", 403, payload)
}

func (o *GetCatalogItemForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /catalog/2022-04-01/items/{asin}][%d] getCatalogItemForbidden %s", 403, payload)
}

func (o *GetCatalogItemForbidden) GetPayload() *models.ErrorList {
	return o.Payload
}

func (o *GetCatalogItemForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header x-amzn-RequestId
	hdrXAmznRequestID := response.GetHeader("x-amzn-RequestId")

	if hdrXAmznRequestID != "" {
		o.XAmznRequestID = hdrXAmznRequestID
	}

	o.Payload = new(models.ErrorList)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCatalogItemNotFound creates a GetCatalogItemNotFound with default headers values
func NewGetCatalogItemNotFound() *GetCatalogItemNotFound {
	return &GetCatalogItemNotFound{}
}

/*
GetCatalogItemNotFound describes a response with status code 404, with default header values.

The resource specified does not exist.
*/
type GetCatalogItemNotFound struct {

	/* Your rate limit (requests per second) for this operation.
	 */
	XAmznRateLimitLimit string

	/* Unique request reference identifier.
	 */
	XAmznRequestID string

	Payload *models.ErrorList
}

// IsSuccess returns true when this get catalog item not found response has a 2xx status code
func (o *GetCatalogItemNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get catalog item not found response has a 3xx status code
func (o *GetCatalogItemNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get catalog item not found response has a 4xx status code
func (o *GetCatalogItemNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get catalog item not found response has a 5xx status code
func (o *GetCatalogItemNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get catalog item not found response a status code equal to that given
func (o *GetCatalogItemNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get catalog item not found response
func (o *GetCatalogItemNotFound) Code() int {
	return 404
}

func (o *GetCatalogItemNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /catalog/2022-04-01/items/{asin}][%d] getCatalogItemNotFound %s", 404, payload)
}

func (o *GetCatalogItemNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /catalog/2022-04-01/items/{asin}][%d] getCatalogItemNotFound %s", 404, payload)
}

func (o *GetCatalogItemNotFound) GetPayload() *models.ErrorList {
	return o.Payload
}

func (o *GetCatalogItemNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header x-amzn-RateLimit-Limit
	hdrXAmznRateLimitLimit := response.GetHeader("x-amzn-RateLimit-Limit")

	if hdrXAmznRateLimitLimit != "" {
		o.XAmznRateLimitLimit = hdrXAmznRateLimitLimit
	}

	// hydrates response header x-amzn-RequestId
	hdrXAmznRequestID := response.GetHeader("x-amzn-RequestId")

	if hdrXAmznRequestID != "" {
		o.XAmznRequestID = hdrXAmznRequestID
	}

	o.Payload = new(models.ErrorList)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCatalogItemRequestEntityTooLarge creates a GetCatalogItemRequestEntityTooLarge with default headers values
func NewGetCatalogItemRequestEntityTooLarge() *GetCatalogItemRequestEntityTooLarge {
	return &GetCatalogItemRequestEntityTooLarge{}
}

/*
GetCatalogItemRequestEntityTooLarge describes a response with status code 413, with default header values.

The request size exceeded the maximum accepted size.
*/
type GetCatalogItemRequestEntityTooLarge struct {

	/* Unique request reference identifier.
	 */
	XAmznRequestID string

	Payload *models.ErrorList
}

// IsSuccess returns true when this get catalog item request entity too large response has a 2xx status code
func (o *GetCatalogItemRequestEntityTooLarge) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get catalog item request entity too large response has a 3xx status code
func (o *GetCatalogItemRequestEntityTooLarge) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get catalog item request entity too large response has a 4xx status code
func (o *GetCatalogItemRequestEntityTooLarge) IsClientError() bool {
	return true
}

// IsServerError returns true when this get catalog item request entity too large response has a 5xx status code
func (o *GetCatalogItemRequestEntityTooLarge) IsServerError() bool {
	return false
}

// IsCode returns true when this get catalog item request entity too large response a status code equal to that given
func (o *GetCatalogItemRequestEntityTooLarge) IsCode(code int) bool {
	return code == 413
}

// Code gets the status code for the get catalog item request entity too large response
func (o *GetCatalogItemRequestEntityTooLarge) Code() int {
	return 413
}

func (o *GetCatalogItemRequestEntityTooLarge) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /catalog/2022-04-01/items/{asin}][%d] getCatalogItemRequestEntityTooLarge %s", 413, payload)
}

func (o *GetCatalogItemRequestEntityTooLarge) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /catalog/2022-04-01/items/{asin}][%d] getCatalogItemRequestEntityTooLarge %s", 413, payload)
}

func (o *GetCatalogItemRequestEntityTooLarge) GetPayload() *models.ErrorList {
	return o.Payload
}

func (o *GetCatalogItemRequestEntityTooLarge) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header x-amzn-RequestId
	hdrXAmznRequestID := response.GetHeader("x-amzn-RequestId")

	if hdrXAmznRequestID != "" {
		o.XAmznRequestID = hdrXAmznRequestID
	}

	o.Payload = new(models.ErrorList)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCatalogItemUnsupportedMediaType creates a GetCatalogItemUnsupportedMediaType with default headers values
func NewGetCatalogItemUnsupportedMediaType() *GetCatalogItemUnsupportedMediaType {
	return &GetCatalogItemUnsupportedMediaType{}
}

/*
GetCatalogItemUnsupportedMediaType describes a response with status code 415, with default header values.

The request payload is in an unsupported format.
*/
type GetCatalogItemUnsupportedMediaType struct {

	/* Unique request reference identifier.
	 */
	XAmznRequestID string

	Payload *models.ErrorList
}

// IsSuccess returns true when this get catalog item unsupported media type response has a 2xx status code
func (o *GetCatalogItemUnsupportedMediaType) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get catalog item unsupported media type response has a 3xx status code
func (o *GetCatalogItemUnsupportedMediaType) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get catalog item unsupported media type response has a 4xx status code
func (o *GetCatalogItemUnsupportedMediaType) IsClientError() bool {
	return true
}

// IsServerError returns true when this get catalog item unsupported media type response has a 5xx status code
func (o *GetCatalogItemUnsupportedMediaType) IsServerError() bool {
	return false
}

// IsCode returns true when this get catalog item unsupported media type response a status code equal to that given
func (o *GetCatalogItemUnsupportedMediaType) IsCode(code int) bool {
	return code == 415
}

// Code gets the status code for the get catalog item unsupported media type response
func (o *GetCatalogItemUnsupportedMediaType) Code() int {
	return 415
}

func (o *GetCatalogItemUnsupportedMediaType) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /catalog/2022-04-01/items/{asin}][%d] getCatalogItemUnsupportedMediaType %s", 415, payload)
}

func (o *GetCatalogItemUnsupportedMediaType) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /catalog/2022-04-01/items/{asin}][%d] getCatalogItemUnsupportedMediaType %s", 415, payload)
}

func (o *GetCatalogItemUnsupportedMediaType) GetPayload() *models.ErrorList {
	return o.Payload
}

func (o *GetCatalogItemUnsupportedMediaType) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header x-amzn-RequestId
	hdrXAmznRequestID := response.GetHeader("x-amzn-RequestId")

	if hdrXAmznRequestID != "" {
		o.XAmznRequestID = hdrXAmznRequestID
	}

	o.Payload = new(models.ErrorList)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCatalogItemTooManyRequests creates a GetCatalogItemTooManyRequests with default headers values
func NewGetCatalogItemTooManyRequests() *GetCatalogItemTooManyRequests {
	return &GetCatalogItemTooManyRequests{}
}

/*
GetCatalogItemTooManyRequests describes a response with status code 429, with default header values.

The frequency of requests was greater than allowed.
*/
type GetCatalogItemTooManyRequests struct {

	/* Unique request reference identifier.
	 */
	XAmznRequestID string

	Payload *models.ErrorList
}

// IsSuccess returns true when this get catalog item too many requests response has a 2xx status code
func (o *GetCatalogItemTooManyRequests) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get catalog item too many requests response has a 3xx status code
func (o *GetCatalogItemTooManyRequests) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get catalog item too many requests response has a 4xx status code
func (o *GetCatalogItemTooManyRequests) IsClientError() bool {
	return true
}

// IsServerError returns true when this get catalog item too many requests response has a 5xx status code
func (o *GetCatalogItemTooManyRequests) IsServerError() bool {
	return false
}

// IsCode returns true when this get catalog item too many requests response a status code equal to that given
func (o *GetCatalogItemTooManyRequests) IsCode(code int) bool {
	return code == 429
}

// Code gets the status code for the get catalog item too many requests response
func (o *GetCatalogItemTooManyRequests) Code() int {
	return 429
}

func (o *GetCatalogItemTooManyRequests) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /catalog/2022-04-01/items/{asin}][%d] getCatalogItemTooManyRequests %s", 429, payload)
}

func (o *GetCatalogItemTooManyRequests) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /catalog/2022-04-01/items/{asin}][%d] getCatalogItemTooManyRequests %s", 429, payload)
}

func (o *GetCatalogItemTooManyRequests) GetPayload() *models.ErrorList {
	return o.Payload
}

func (o *GetCatalogItemTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header x-amzn-RequestId
	hdrXAmznRequestID := response.GetHeader("x-amzn-RequestId")

	if hdrXAmznRequestID != "" {
		o.XAmznRequestID = hdrXAmznRequestID
	}

	o.Payload = new(models.ErrorList)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCatalogItemInternalServerError creates a GetCatalogItemInternalServerError with default headers values
func NewGetCatalogItemInternalServerError() *GetCatalogItemInternalServerError {
	return &GetCatalogItemInternalServerError{}
}

/*
GetCatalogItemInternalServerError describes a response with status code 500, with default header values.

An unexpected condition occurred that prevented the server from fulfilling the request.
*/
type GetCatalogItemInternalServerError struct {

	/* Unique request reference identifier.
	 */
	XAmznRequestID string

	Payload *models.ErrorList
}

// IsSuccess returns true when this get catalog item internal server error response has a 2xx status code
func (o *GetCatalogItemInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get catalog item internal server error response has a 3xx status code
func (o *GetCatalogItemInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get catalog item internal server error response has a 4xx status code
func (o *GetCatalogItemInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get catalog item internal server error response has a 5xx status code
func (o *GetCatalogItemInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get catalog item internal server error response a status code equal to that given
func (o *GetCatalogItemInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get catalog item internal server error response
func (o *GetCatalogItemInternalServerError) Code() int {
	return 500
}

func (o *GetCatalogItemInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /catalog/2022-04-01/items/{asin}][%d] getCatalogItemInternalServerError %s", 500, payload)
}

func (o *GetCatalogItemInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /catalog/2022-04-01/items/{asin}][%d] getCatalogItemInternalServerError %s", 500, payload)
}

func (o *GetCatalogItemInternalServerError) GetPayload() *models.ErrorList {
	return o.Payload
}

func (o *GetCatalogItemInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header x-amzn-RequestId
	hdrXAmznRequestID := response.GetHeader("x-amzn-RequestId")

	if hdrXAmznRequestID != "" {
		o.XAmznRequestID = hdrXAmznRequestID
	}

	o.Payload = new(models.ErrorList)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCatalogItemServiceUnavailable creates a GetCatalogItemServiceUnavailable with default headers values
func NewGetCatalogItemServiceUnavailable() *GetCatalogItemServiceUnavailable {
	return &GetCatalogItemServiceUnavailable{}
}

/*
GetCatalogItemServiceUnavailable describes a response with status code 503, with default header values.

Temporary overloading or maintenance of the server.
*/
type GetCatalogItemServiceUnavailable struct {

	/* Unique request reference identifier.
	 */
	XAmznRequestID string

	Payload *models.ErrorList
}

// IsSuccess returns true when this get catalog item service unavailable response has a 2xx status code
func (o *GetCatalogItemServiceUnavailable) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get catalog item service unavailable response has a 3xx status code
func (o *GetCatalogItemServiceUnavailable) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get catalog item service unavailable response has a 4xx status code
func (o *GetCatalogItemServiceUnavailable) IsClientError() bool {
	return false
}

// IsServerError returns true when this get catalog item service unavailable response has a 5xx status code
func (o *GetCatalogItemServiceUnavailable) IsServerError() bool {
	return true
}

// IsCode returns true when this get catalog item service unavailable response a status code equal to that given
func (o *GetCatalogItemServiceUnavailable) IsCode(code int) bool {
	return code == 503
}

// Code gets the status code for the get catalog item service unavailable response
func (o *GetCatalogItemServiceUnavailable) Code() int {
	return 503
}

func (o *GetCatalogItemServiceUnavailable) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /catalog/2022-04-01/items/{asin}][%d] getCatalogItemServiceUnavailable %s", 503, payload)
}

func (o *GetCatalogItemServiceUnavailable) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /catalog/2022-04-01/items/{asin}][%d] getCatalogItemServiceUnavailable %s", 503, payload)
}

func (o *GetCatalogItemServiceUnavailable) GetPayload() *models.ErrorList {
	return o.Payload
}

func (o *GetCatalogItemServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header x-amzn-RequestId
	hdrXAmznRequestID := response.GetHeader("x-amzn-RequestId")

	if hdrXAmznRequestID != "" {
		o.XAmznRequestID = hdrXAmznRequestID
	}

	o.Payload = new(models.ErrorList)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
