// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
)

type FbaInventory struct {
	Title                    sql.NullString
	TotalQuantity            sql.NullInt64
	FulfillableQuantity      sql.NullInt64
	InboundReceivingQuantity sql.NullInt64
	InboundShippedQuantity   sql.NullInt64
	Sku                      sql.NullString
	Asin                     sql.NullString
}
